COINES_INSTALL_PATH ?= ../../../../..

EXAMPLE_FILE ?= gyro_fifo_full.c

API_LOCATION ?= ../../..

C_SRCS += \
$(API_LOCATION)/bmi08a.c \
$(API_LOCATION)/bmi08g.c \
$(API_LOCATION)/bmi08xa.c \
../common/common.c

INCLUDEPATHS += \
$(API_LOCATION) \
../common

include $(COINES_INSTALL_PATH)/coines.mk